name: Update Destin, Florida Beach Flag Status

on:
  repository_dispatch:
    types: [destin-flags-update]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Beach Status File
        run: |
          # Ensure the directory exists
          mkdir -p flag-status
          
          # Write the message payload to the text file
          echo "${{ github.event.client_payload.message }}" > flag-status/panama-city-beach.txt
          
          # Configure Git
          git config user.name "Paul Rosenthal"
          git config user.email "Paul.H.Rosenthal@iCloud.com"
          
          # Add, commit, and push changes
          git add flag-status/panama-city-beach.txt
          git commit -m "[Automatic Commit] Update Panama City Beach Flag Status"
          git push
